default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: <%= ENV.fetch('DATABASE_URL', nil) || 'marketer_plus_development' %>


test:
  <<: *default
  database: <%= ENV.fetch('DATABASE_TEST_URL', nil) || 'marketer_plus_test' %>

production:
  primary:
    <<: *default
    url: <%= ENV.fetch('DATABASE_URL', nil) || 'marketer_plus' %>